// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBCnBHwJfiuxfSSH95OtmLTzRI-r1SV0',
    appId: '1:830473395777:web:f60743b07947ce0f6bb0c0',
    messagingSenderId: '830473395777',
    projectId: 'action-engine-dev-2',
    authDomain: 'action-engine-dev-2.firebaseapp.com',
    storageBucket: 'action-engine-dev-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9amKl5dCv45ZdzqE_bBfcGSqVMtHvBU',
    appId: '1:830473395777:android:4a38d54aa8ec73b36bb0c0',
    messagingSenderId: '830473395777',
    projectId: 'action-engine-dev-2',
    storageBucket: 'action-engine-dev-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fV06ysLtYgUJJG_2L4S5eoscGEtCVD0',
    appId: '1:830473395777:ios:09bd0d31c34b043b6bb0c0',
    messagingSenderId: '830473395777',
    projectId: 'action-engine-dev-2',
    storageBucket: 'action-engine-dev-2.appspot.com',
    iosBundleId: 'com.example.actionEngine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fV06ysLtYgUJJG_2L4S5eoscGEtCVD0',
    appId: '1:830473395777:ios:09bd0d31c34b043b6bb0c0',
    messagingSenderId: '830473395777',
    projectId: 'action-engine-dev-2',
    storageBucket: 'action-engine-dev-2.appspot.com',
    iosBundleId: 'com.example.actionEngine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQBCnBHwJfiuxfSSH95OtmLTzRI-r1SV0',
    appId: '1:830473395777:web:78eedc6e145f850d6bb0c0',
    messagingSenderId: '830473395777',
    projectId: 'action-engine-dev-2',
    authDomain: 'action-engine-dev-2.firebaseapp.com',
    storageBucket: 'action-engine-dev-2.appspot.com',
  );

}